### ISSUE TITLE
Erro - state.JSON FileNotFoundError

### ISSUE THREAD

**Issue by diogoalmiro** [joaovizoso/workflow1.0#1]
Não meteste um `state.JSON` na pasta `tmp`. E o `docManager.get_data` não verifica se este existe: 
```
[14:15] diogoalmiro ~/Desktop/ARMS FILES/workflow1.0/exec (master)$ python workflow.py 
Traceback (most recent call last):
  File "/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/workflow.py", line 33, in <module>
    main()
  File "/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/workflow.py", line 25, in main
    docManager.write_name()
  File "/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/docManager.py", line 16, in write_name
    if check_name(file):
  File "/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/docManager.py", line 26, in check_name
    data = get_data()
  File "/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/docManager.py", line 87, in get_data
    with path.open() as file:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/diogoalmiro/Desktop/ARMS FILES/workflow1.0/exec/tmp/state.JSON'
```
Fazer um `try: ... except: return []` parece fazer isto funcionar. Outra sugestão é fazeres a verificação como no check_name (`file.is_file()`) para o docs.JSON.

**Comment by joaovizoso** [comment]
Tinha mudado o nome do ficheiro e esqueci-me de mudar no código
